export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "../globals.css";


export default function RootLayout({
  children,
  invoicetable,
}: {
  children: React.ReactNode;
  invoicetable: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

          {children}
          <div className="px-20 py-5">{invoicetable}</div>

      </body>
    </html>
  );
}
